# Generated by Django 5.2.3 on 2025-06-23 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamproductivity', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Developer',
            new_name='Teams',
        ),
    ]
