# Generated by Django 5.2.3 on 2025-06-23 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamproductivity', '0002_rename_developer_teams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='developer',
            new_name='team',
        ),
    ]
